### ISSUE TITLE
Create a orchard-recipies repo please

### ISSUE THREAD

**Issue by mjung** [autopkg/recipes#114]
Hi.

Would be nice to have an orchard-recipes repo please for the Oxford team to make our lovely new recipes discoverable.

Thanks,
Marko

**Comment by gregneagle** [comment]
Here's how you can make that happen: https://github.com/autopkg/autopkg/wiki/Sharing-Recipes

**Comment by mjung** [comment]
I would rather prefer this not being a fork, but here you go:
https://github.com/ox-it/orchard-recipes/
I even changed the README.md to fulfil this requirement.

**Comment by gregneagle** [comment]
"I would rather prefer this not being a fork"

You have a few choices:

1) Leave the repo at https://github.com/ox-it/orchard-recipes/. People won't be able to discover it it by browsing https://github.com/autopkg, and `autopkg search` will not by default search your recipe repo.

2) Let us fork it under https://github.com/autopkg/, and maintain both your repo and the one under the autopkg organization.

3) Let us fork it under https://github.com/autopkg/, and abandon/remove your repo. You can then do all future maintenance in the repo's new home.

**Comment by bochoven** [comment]
My advise: choose #3

**Comment by mjung** [comment]
Please fork https://github.com/ox-it/orchard-recipes and grant me the permissions.
Thank you.

**Comment by timsutton** [comment]
Thanks! Just took a look, and noticed a few duplicates of recipes already available:

Inkscape -> homebysix
Mou -> homebysix
Soundflower -> hansen-m
VirtualBox -> jessepeterson

Generally we try to avoid having duplicate recipes if they're functionally equivalent. If the author would rather continue using their own recipe they've already created, we suggest he/she remove this from the proposed new repo so as to minimize confusion by users searching for recipes.

If there's a functional difference between yours and the existing recipe that's fine, as long as it's documented in Description.

**Comment by mjung** [comment]
I struggle to see an advantage in only granting people who write a recipe
first the right to publish it in a searchable repo. Furthermore, there is
already a lot of duplication.

**Comment by gregneagle** [comment]
The desire is to reduce confusion for people using autopkg. They do `autopkg search VirtualBox` and get two recipes back. Which to choose? If you think your recipe is better, then describe its superior qualities in the recipe description and keep it in your repo. If, however you look at both recipes and see that they are functionally equivalent, it would be kinder to other autopkg users to remove your recipe to reduce confusion.

**Comment by timsutton** [comment]
While is duplication out there already, wherever possible we encourage people to instead contribute to any existing recipes that already do the same thing. It's not about a privilege given to whoever was first, but rather, as Greg said, to reduce confusion.

One case is the user just searching for recipes and not sure which to pick, but another case is the situation where one recipe is broken and another is not - for whatever reason, maybe the maintainer of the broken recipe no longer needs it and isn't motivated to fix it. Either way, it results in some duplication of effort by users who may have picked and overridden one recipe that's now no longer working. By striving to avoid creating this scenario from the beginning, there's a higher likelihood that when someone tries a new recipe for the first time that it will work as expected, because there will be a higher concentration of AutoPkg users willing to combine efforts to help fix the _one_ canonical recipe rather than two or three that do the same thing.

Plus, fewer recipes for _you_ to maintain! And if you really do want to maintain them, you still can privately. Or if you think yours are better than the existing ones, then try to work with the maintainer to see if he/she can integrate your improvements.

**Comment by fuzzylogiq** [comment]
OK I've moved these away.

Inkscape - this was written locally to fix a problem with the original that didn't seem like it was getting fixed, but I note there have been some recent changes, so I will test the changes.
Mou - oversight on our part
Soundflower - this has been abandoned by cycling74 and taken over by rogueamoeba. I will contact the original author, I wrote this as a test and this shouldn't really have been pushed.
Virtualbox - was removed in commit when I realised it was a duplicate

Hopefully should be good to go now.

**Comment by timsutton** [comment]
Thanks. I'm in the process of finally updating our setup script to handle repos from orgs.

Would you like the repo name to be "orchard-recipes" or "ox-it-recipes"?

**Comment by fuzzylogiq** [comment]
orchard-recipes please

**Comment by timsutton** [comment]
Done!

**Comment by timsutton** [comment]
https://github.com/autopkg/orchard-recipes

**Comment by mjung** [comment]
Thanks. I did not find an option to invite other members to the team.
Can someone please add
- https://github.com/fuzzylogiq
- https://github.com/cdbeard

Sorry to bother you. Thanks.

**Comment by timsutton** [comment]
I just promoted you to a team maintainer, which should now give you the ability to manage other team members. I think this is a relatively new addition to the Organizations permissions system - the API for this is still in a preview stage. In the past each team has only consisted of one member for one repo.
