### ISSUE TITLE
munkitools2.munki.recipe - admin as update for core?

### ISSUE THREAD

**Issue by VitosX** [autopkg/recipes#147]
I was wondering why munkitools_admin package is configured as an update for munkitools_core?
It triggers unnecessary admin commandline tools installations on end clients.

**Comment by timsutton** [comment]
The author(s) of the munkitools2 recipes tend to install the admin tools on end clients along with the rest of the Munki packages.

There's not currently a way for the recipe to skip these. A few choices:

* Maintain your own recipe that removes the MunkiImporter step importing the admin tools.
* When AutoPkg imports the admin tools, just don't add the admin tools to your production clients (it may well useful for you to have them on any testing clients, in any case)
* Propose a way and submit a PR, so that the recipe could support this with an Input variable. The only simple way I'd see this being possible would be to change the order of processing so that the admin tools are done last, and use a StopProcessingIf step before that checks whether the user has set some "SKIP_ADMIN_PKG" input variable.

**Comment by gregneagle** [comment]
That's a lot of work to avoid installing the admin tools. There's almost zero reason to avoid installing the admin tools; they are no more "dangerous" to have installed than is having "vi", "nano", "PlistBuddy", or a GUI text editor installed.

**Comment by VitosX** [comment]
Sure, there is not much danger having them. It just looked for me as kind of overlook to treat admin package as an update. I didn't expect to see such author(s) personal preferences influence in a default (if I may call it that way) autopkg recipes repo.
