### ISSUE TITLE
Puppet-agent.munki Max OS Version

### ISSUE THREAD

**Issue by anatomism** [autopkg/recipes#180]
When I imported the puppet agent into MunkiAdmin via AutoPkgr is gave a maximum OS version as '10.10.99' rather than the desired '10.12.99' (running 10.12 Sierra).

Not able to test currently, not sure why it would, looking at the code

**Comment by timsutton** [comment]
This is because PL used to make individual OS version installers for the Puppet Agent. If this is no longer the case, perhaps the recipe should be modified to just retrieve the latest version available. Would be nice to know from someone who's involved with the Puppet Agent for Mac releases so we don't have to guess, though.

**Comment by hjuutilainen** [comment]
Puppet still offers different builds for different OS versions (even though the version and package receipts are identical) so I'd say the recipe is correct and current.

**Comment by timsutton** [comment]
So it looks like you just need to make an override to set `OS_VERSION` to `10.12` (and repeat for every OS version you want to support).
