### ISSUE TITLE
Handbrake.download fails with 404 Not Found

### ISSUE THREAD

**Issue by brianwells** [autopkg/recipes#181]
Handbrake.download fails with 404 Not Found due to a broken Sparkle feed, which lists the old version (0.10.5) instead of current version (1.0.0). The download URLs provided by the feed for version 0.10.5 have already been discontinued and thus result in the 404 Not Found error.

```Processor: URLDownloader: Error: Curl failure: The requested URL returned error: 404 Not Found (exit code 22)```

**Comment by brianwells** [comment]
Submitted issue with Handbrake project: HandBrake/HandBrake#447 and they indicate that the feed is broken deliberately as part of rolling out the new version of Handbrake. They say it will be fixed in a few days.

**Comment by gregneagle** [comment]
Have you reported the broken Sparkle feed to the vendor?

Wouldn't this prevent Sparkle from discovering its own updates?

**Comment by gregneagle** [comment]
Seems like there is nothing that should be done for the autopkg recipe, then. One can always manually download the current version if one needs it now and use the --pkg option to use it with non-download recipes.

**Comment by brianwells** [comment]
@gregneagle Yes, I filed an issue with HandBrake project to report the broken Sparkle feed. Unfortunately they responded that they broke the feed on purpose. So anyone who uses the recipe will need to wait until the feed is fixed (or use --pkg option).

**Comment by timsutton** [comment]
This is also not the first time for HandBrake - I remember going through this with then before. It seems not uncommon for OSS projects to want to wait a few days from offering a new version for download until they offer to update everyone else in the wild.

**Comment by brianwells** [comment]
The Sparkle feed has been updated and Handbrake.download recipe works once again.

**Comment by gregneagle** [comment]
Would you mind commenting on the other similar issues? #182 #183

**Comment by bradleysepos** [comment]
Just a quick heads up to let everyone know that this is the desired behavior and not considered breakage. We stagger our rollout for major new releases to avoid traffic spikes and sort out any other issues. Downloads go live on the main website for a few days or a week, and then we update the Sparkle feed. This is intentional, so something to expect and plan for down the road. Cheers.

**Comment by timsutton** [comment]
That all seems reasonable, though I'm curious why bother pulling the item at the existing Sparkle enclosure URL in the process?

**Comment by brianwells** [comment]
@bradleysepos: staggering the rollout is not a problem. The old download going away before the Sparkle feed changes causes the issue. If the old download could stick around for a bit until the feed changes then everything would work fine and we would never notice the staggered rollout. Just a suggestion. :)

**Comment by bradleysepos** [comment]
Ah, I wasn't aware that was happening. That does seem like breakage. Thanks for clarifying; @sr55 may be able to confirm whether that's automated.

**Comment by sr55** [comment]
Our Appcast feeds were never meant for 3rd party use so we manage them in a way that's easy for us, not for 3rd parties.

So, don't be surprised to see the feeds non-functional around releases.

**Comment by timsutton** [comment]
Thanks for the feedback! I realize that for Sparkle's intended use that a broken URL doesn't pose a problem.

We could instead switch this recipe to URLTextSearcher to avoid these issues with future releases.

I know historically that HandBrake official releases have been quite infrequent (although I know the code base is very active). With the jump to 1.x, do you foresee releases being more frequent and in smaller increments?

**Comment by sr55** [comment]
Probably several 1.0.x releases this year.  Can't say for sure about 1.y.x releases. Hopefully at least one this year.

**Comment by bradleysepos** [comment]
We switched to [SemVer](http://semver.org/) with 0.10.0, which turned out to be our most successful and stable release series yet with five subsequent patch releases. Basically, we fixed as many bugs as possible and pushed those bug fixes to end users, until the only remaining bug fixes were ones requiring significant enough internal overhauling to warrant a minor revision bump. Those more significant changes and additions (e.g. improvements to a/v sync engine that fixed a variety of flaky sources) were on the master branch and thus tested in the nightly builds for some time, and eventually released with other improvements as 1.0.0. The future should be relatively similar, I imagine.

You can track upcoming milestones at https://github.com/HandBrake/HandBrake/milestones/1.0.2 and https://github.com/HandBrake/HandBrake/milestones/1.1.0. Note that once 1.1.0 is out we will cease updating 1.0.x; we typically only support one major/minor release at a time.

**Comment by timsutton** [comment]
Thanks for taking the time to provide those details here!
