### ISSUE TITLE
Override for MSOffice2016 recipes is not overriding pkginfo from MSOffice2016URLandUpdateInfoProvider.py

### ISSUE THREAD

**Issue by carlashley** [autopkg/recipes#206]
I have created an override for the Word/Excel/PowerPoint 2016 recipes that modifies keys in the `pkginfo` dict for the `munki` recipes. One of those keys is the `description` key.
When the override is run, the `description` in the override is not used, but the one generated from `MSOffice2016URLandUpdateInfoProvider.py` is used.

I'm curious if this intended behaviour? I'd prefer it not be, as expected behaviour is that an override should override any default info generated by processors.
My use case is to provide a custom description that includes URL's to screenshots and other specific descriptions of apps.

**Comment by timsutton** [comment]
My recommendation here would be that in `MSOffice2016URLandUpdateInfoProvider`, if `self.env['pkginfo']['description']` exists at the start of the run, we don't clobber this with what we've parsed from the update feed, and just leave it as-is. This should be a pretty straightforward change if someone would be willing to add and test.

**Comment by gregneagle** [comment]
But that's special-casing "description". What if the next person wants to override some other pkginfo key auto-generated by the processor? A more general solution is needed.

**Comment by timsutton** [comment]
Sure. This may well make sense for _every_ top-level pkginfo key generated by the processor, to first check if there was a user-defined one from the Input. `display_name`, for example.

Related: the Sparkle processor has some functionality along these lines, where the admin can instruct the processor to copy some additional keys to the pkginfo (minimum os version and descriptions as parsed from the feed XML), but this is opt-in rather than opt-out. I imagine there could be some nicer way for AutoPkg core to handle this, but making it easy enough to use or comprehend is probably the bigger challenge, especially given that currently, custom processors can still modify the `env` however they wish.

**Comment by carlashley** [comment]
Thanks @timsutton for the pointer where to look. For the time being, I'm using the below to get the ~droids~ outcome I'm looking for:

```
        try:
            manifest_description = self.env["pkginfo"]["description"]
        except:
            manifest_description = all_localizations[lcid]['Short Description']
```
