### ISSUE TITLE
VLC Recipe not pulling in versions newer than 2.2.4

### ISSUE THREAD

**Issue by pereiraa-wellesleyps** [autopkg/recipes#211]
AutoPkg (with AutoPkgr front-end) repeatedly downloads VLC 2.2.4, but does not download newer versions (e.g., VLC 2.2.6).

**Comment by timsutton** [comment]
The Videolan VLC devs tend to be conservative in updating the Mac Sparkle feed and instead prefer to publish the new versions to their website only for a while, as a way to catch any issues before a majority of their existing users update via Sparkle.

Since the developers don't seem to want to update everyone to the newest versions for a while I tend towards us not doing that either - but if you want to import the latest version, you can download it manually and run the recipe using the `--pkg <path/to/dmg>` option.

See #82 and #10.

**Comment by pereiraa-wellesleyps** [comment]
Ah, so when the sparkle feed updates, the VLC Recipe should, as well?

--
Anthony Pereira
Systems Administrator
Wellesley Public Schools
pereiraa@wellesleyps.org
781-446-6210 x5451

**Comment by timsutton** [comment]
Yes. It just seems like for whatever reason, they're taking even longer than usual to do it for the Mac build. Also, it seems to me like 2.2.6 is not available for macOS.

**Comment by tallfunnyjew** [comment]
well that explains the delay in posting 3.0 to sparkle feed then. thx.
