### ISSUE TITLE
SassafrasK2Client not downloading the latest version

### ISSUE THREAD

**Issue by cowiea310** [autopkg/recipes#279]
Looks like the last version it downloaded was 7.4.2.0 and they are releasing 7.5.06

**Comment by jazzace** [comment]
The recipe is working for me. If you have specified a value of 74 in REVISION (which is the default value), then it will not download anything past 7.4.x.x. If you change your override so that the value for REVISION is empty, then it will download the latest version, regardless of minor version. I believe this issue should be closed, although I may put in a PR to change the default value for REVISION to empty.

**Comment by macmule** [comment]
@jazzace Commenting on the recipe in: https://github.com/autopkg/recipes/issues/279

Setting the "REVISION" to empty is not picking up the latest version for me, will sort that before confirming.

**Comment by macmule** [comment]
doh! actually need to be set empty.. NOT removed..

The below works:

```		<key>REVISION</key>
		<string/>```

**Comment by apizz** [comment]
Can this be closed?

**Comment by jazzace** [comment]
Agreed that it can be closed. I have also made the PR I suggested in my earlier post, so there are no outstanding issues, even from a usability standpoint.
