### ISSUE TITLE
Google Chrome pkg

### ISSUE THREAD

**Issue by kylejericson** [autopkg/recipes#289]
Does this recipe disable auto updates on newest version on Chrome 73? I installed this on a vm and gives an error saying Google Chrome can't update itself.

**Comment by homebysix** [comment]
@kylejericson This might be related to the permissions of the Chrome pkg, not the AutoPkg recipe itself. I've found admin users observe the same behavior when I deploy Chrome with `755` permissions (typical of others in the /Applications folder) instead of `775` permissions.

Does `sudo chmod -R g+w "/Applications/Google Chrome.app"` resolve the "can't update" error for an admin user on a test Mac?

**Comment by rx7raven** [comment]
This fixed the error "Google Chrome can't update itself" for my test machine.

**Comment by homebysix** [comment]
@rx7raven Do you get those rsync errors during AutoPkg recipe run, or during install of the resulting package on a test Mac?

**Comment by rx7raven** [comment]
That's after deploying the PKG from Autopkgr.  I ran the '''sudo chmod -R g+w "/Applications/Google Chrome.app" command and that pops up in Google Chrome when trying to update.

**Comment by homebysix** [comment]
I haven't been able to reproduce this issue.

**Comment by gregneagle** [comment]
Closing this as out-of-date and possibly made irrelevant by the official chrome package from Google.
