### ISSUE TITLE
VLC Apple Silicone Sparkle Feed

### ISSUE THREAD

**Issue by carlashley** [autopkg/recipes#381]
This isn't so much a "problem" as an "FYI" - VLC has a seperate Apple Silicone build and the Sparkle update feed appears to be available here: https://update.videolan.org/vlc/sparkle/vlc-arm64.xml

**Comment by homebysix** [comment]
Created PR to address: https://github.com/autopkg/recipes/pull/385

**Comment by MichalMMac** [comment]
There is now an UB build. Its url should be `https://update.videolan.org/vlc/sparkle/vlc.xml `

**Comment by homebysix** [comment]
Good callout.

According to [Charles](https://www.charlesproxy.com/), the new Universal build is using the same Sparkle feed URL as the Intel version.

![Screen Shot 2021-09-21 at 5 43 43 AM](https://user-images.githubusercontent.com/7801391/134172698-47d83092-096b-43cc-8938-769dd9898ddd.png)

Let's keep an eye on it — I suspect the Universal version will get its own feed, but may not have been a top priority for this latest release. If not, maybe we could consider using URLTextSearcher.

**Comment by homebysix** [comment]
Thanks @ResidentChief, that's clever. I'd rather not update the main VLC.download recipe to check multiple sources, though. Best case, VLC Universal gets its own Sparkle feed. Next best, we use URLTextSearcher to get the version number directly from the download page, then use URLDownloader to construct the download URL (as you've done above).

I'm starting to lean towards enacting the "next best" option while we wait for the "best" option.

**Comment by homebysix** [comment]
I've submitted https://github.com/autopkg/recipes/pull/410, which switches the download source to the Universal version of VLC.

Read the IMPORTANT note in that PR. TLDR: all AutoPkg users will get the Universal version when they `repo-update`, no matter what their previous Sparkle feed setting. They can modify the new `ARCHITECTURE` variable and the `supported_architectures` pkginfo array if they desire otherwise.
