### ISSUE TITLE
VLC version 2.2

### ISSUE THREAD

**Issue by seansgm** [autopkg/recipes#82]
VLC recipe is pulling version 2.1.5
SparkleUpdateInfoProvider: Found URL http://get.videolan.org/vlc/2.1.5/macosx/vlc-2.1.5.dmg

 latest version is 2.2.0
http://get.videolan.org/vlc/2.2.0/macosx/vlc-2.2.0.dmg

**Comment by gregneagle** [comment]
2.1.5 is the latest version referenced by the Sparkle update feed.

Until the VLC devs update that feed, you can download the dmg from the URL you give above, and run any recipes with the --pkg flag:

`autopkg run VLC.munki --pkg /path/to/downloaded/vlc-2.2.0.dmg`

**Comment by timsutton** [comment]
Also for more background: #81, https://github.com/autopkg/recipes/issues/10#issuecomment-26617525

**Comment by n8felton** [comment]
From #videolan on freenode

(4:52:06 PM) n8felton: Hey guys, I'm going to check Trac and all that jazz, but I was wondering if anyone in here had a quick answer about when the sparkle feed at http://update.videolan.org/vlc/sparkle/vlc-intel64.xml might be updated to reflect the latest version (2.2.0). It looks like the feed hasn't been updated since 24 Jul 2014
(4:55:26 PM) thresh: when we are sure there are no more major crashes in 2.2.21
(4:55:32 PM) thresh: 2.2.1 sorry
(4:56:17 PM) thresh: not cool telling people to upgrade to a version that is supposed to be kinda testing
(4:56:44 PM) n8felton: So 2.1.5 is what's on the feed because it's the latest 'stable'
(4:57:36 PM) thresh: well technically 2.2.0 is a latest stable, but you got the idea
(4:58:02 PM) n8felton: Alright, thanks.
(4:58:42 PM) thresh: 2.2.1 is out real soon and if its fine (which it should be), the feeds will be updated

**Comment by timsutton** [comment]
Thanks - that seems to match what someone else reported as well: https://github.com/autopkg/recipes/issues/81#issuecomment-86505247

**Comment by gregneagle** [comment]
The VLC devs seem to have a bit of a split personality, since version 2.2.0 is featured for download on the main page: http://www.videolan.org/vlc/index.html; but perhaps their thinking is that it's fine if people go looking for the latest version, but they don't want the autoupdate mechanism pushing a version they aren't convinced is stable.

**Comment by seansgm** [comment]
Sorry, should have checked for other comments regarding this.  

I did think it was a little strange since 2.2.0 has been out for a while now which was why I mentioned it.

**Comment by n8felton** [comment]
[videolan-announce] VLC 2.2.1 is out!
https://mailman.videolan.org/pipermail/videolan-announce/2015-April/000169.html

The feed doesn't appear to be updated yet though.

**Comment by n8felton** [comment]
Feed has been updated to include 2.2.1.
