### ISSUE TITLE
Skype downloading already downloaded version

### ISSUE THREAD

**Issue by seansgm** [autopkg/recipes#88]
On 28th May Skype 7.8 was downloaded and pushed to our Absolute server.
On 30th May and today (03 June), the dmg was downloaded again, but same version, so neither of these times was it uploaded to Absolute.

Can I assume that this is the Skype dev team creating new versions without increment the version number?  Sections of this mornings log file below.

Reading the created plist file 'new_downloads'

(
    "/Volumes/DATA/autopkg/Cache/io.github.hjuutilainen.pkg.ExifTool/downloads/ExifTool.dmg",
    "/Volumes/DATA/autopkg/Cache/local.Future.Absolute.Dropbox/downloads/Dropbox.dmg",
    "/Volumes/DATA/autopkg/Cache/local.Future.Absolute.Firefox/downloads/Firefox.dmg",
    "/Volumes/DATA/autopkg/Cache/local.Future.Absolute.Skype/downloads/Skype.dmg"
)

Processing Skype.Absolute.Future.recipe...
URLDownloader
URLDownloader: Storing new Last-Modified header: Tue, 02 Jun 2015 17:46:06 GMT
URLDownloader: Storing new ETag header: "556debde-25414c9"
URLDownloader: Downloaded 

AbsoluteManageExport: [+] [Skype-7.8.pkg] already exists in Absolute Manage Server Center
AbsoluteManageExport: [+] Nothing uploaded to Absolute Manage

**Comment by timsutton** [comment]
Skype has been doing this for a while (they started somewhere in version 6). In the Skype munki recipe, we extract the `CFBundleVersion` from the Info.plist so that we get a nicely-incrementing version:

https://github.com/autopkg/recipes/blob/3d9392a644cb5d414721c6eccc2858d5b086af34/Skype/Skype.munki.recipe#L37-L47

```
Versioner: Mounted disk image /Users/tsutton/Library/AutoPkg/Cache/local.Skype.munki/downloads/Skype.dmg
Versioner: Found version 7.8.0.391 in file /private/tmp/dmg.JmHEf4/Skype.app/Contents/Info.plist
MunkiPkginfoMerger
MunkiPkginfoMerger: Merged {
    version = "7.8.0.391";
} into pkginfo
```

We choose this version and also instruct Munki to use this Info.plist key for comparison on the client.

Since you're commenting on an Absolute recipe and that's not part of this repo, I'm going to close this but recommend you open this issue on the repo containing this recipe instead. Tom's repo may use this download as a `ParentRecipe`, but it's further downstream that the version extraction should be happening.

**Comment by timsutton** [comment]
Should be fixed with a pkg recipe update: https://github.com/autopkg/recipes/commit/4e5da6e6e0c788ba15b748cd5c1028f10dad456f
