### ISSUE TITLE
New puppetlabs open source 'collections' downloads  

### ISSUE THREAD

**Issue by arubdesu** [autopkg/recipes#90]
As announced [here](https://puppetlabs.com/blog/say-hello-open-source-puppet-4), puppet 4 is official and along with that they've [stated their intention](https://puppetlabs.com/blog/welcome-puppet-collections) to bundle dependencies into a 'collection' format. These are available in OS version-specific pkgs, as you can see at this URL: https://downloads.puppetlabs.com/mac/PC1/

The main reason I bring this up is the c++ version of facter doesn't appear to be available elsewhere, even though it's purportedly a .4 version alongside the current ruby one. Not sure how forked the recipes would get if they're splitting by OS for all future releases, but wanted to start the conversation as this may well cause the current recipes to be left checking a deprecated version.

**Comment by timsutton** [comment]
I wonder what are the functional differences for the versions for 10.9 and 10.10 - but if their final versions will have such an OS version distinction, these could be handled with recipe input variables as some other recipes have done.

Since it's not yet the final version, some things about the versioning/naming/downloads may well change - but it seems like it would be easy to add new recipes and slightly extend the Puppetlabs URL provider to handle these new packages. I wouldn't want to merge in any additional recipes until there's a final released version, but if someone wants to get started early, that's up to him/her!

**Comment by timsutton** [comment]
This was added by #98.
